# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
adapter: postgresql
username: postgres
password: kenaur14
port : 5432
host : localhost
pool: 5
timeout: 5000

development:
<<: *default
database: bdd

test:
<<: *default
database: bdd

production:
<<: *default
database: bdd
